### ISSUE TITLE
Move `genToken` function out of data models

### ISSUE THREAD

**Issue by Spindel** [Gingernaut/microAuth#1]
` genToken` is the only thing that requires the models to use global state not tied to the model at all.

split it out into a function that takes a user instance as an argument , and returns said token.

( JWT token data should not be tied to the User model, that way the User model wouldn't be useful in another context)

Why does the data model have both an ID and a UUID?  (It's perfectly valid to have an UUID as the primary key )

**Comment by Gingernaut** [comment]
Hey! Sorry for the long feedback cycle. I've actually re-written the entire project using Sanic now instead of Flask, added lots of testing, and other improvements (if you have some feedback on it now I'd appreciate that). Still have a Integer ID and UUID because I can think of some situtations where it might be nice to have both (such as merging different user databases). The JWT token generation is kept as a helper function on the model since it's only in the user context that a token is created, and it is functionality tied to that user.
