### ISSUE TITLE
Why not use Sanic-JWT?

### ISSUE THREAD

**Issue by martincolladodotcom** [Gingernaut/microAuth#60]
Really like this project, I'm starting to hack with it to fit to a custom project, but the bases are super!. I was wondering why not use the Sanic extension for JWT to adapt de microservice architecture. Also I was wondering to migrate from SQLAlchemy to Gino. What do you think?

**Comment by Gingernaut** [comment]
Hey thanks! At the time I decided to just use PyJWT since I was familiar with it and the implementation/usage is pretty straightforward. That shouldn't have any impact on being able to use it as a microservice; I'm using this as a backend microservice for a project at the moment.

I've looked into Gino a bit (have a comment pointing to it in `db_client.py`) and it looks like a great project, though I'm not sure if an async ORM is worth the potential complexity. [Gino has documentation on the pro's and con's](http://gino.fantix.pro/en/latest/why.html). At the time I went with SQLAlchemy because it's a more battle-tested and mature project. That said, if you use Gino in your project I'd love to hear how that goes, and if the changes are a net benefit an MR here would be great.
